on:
  push:
    branches: ['release-**']
  pull_request:
    branches: ['release-**']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build for Windows and Linux
        shell: bash
        run: |
          mkdir dist
          GOOS=windows GOARCH=amd64 go build -o dist/certse-ioc-converter-win-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o dist/certse-ioc-converter-win-arm64.exe
          GOOS=windows GOARCH=arm go build -o dist/certse-ioc-converter-win-arm.exe
          GOOS=linux GOARCH=amd64 go build -o dist/certse-ioc-converter-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o dist/certse-ioc-converter-linux-arm64
          GOOS=linux GOARCH=arm go build -o dist/certse-ioc-converter-linux-arm

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: README.md
          files: |
            dist/certse-ioc-converter-win-amd64.exe
            dist/certse-ioc-converter-win-arm64.exe
            dist/certse-ioc-converter-win-arm.exe
            dist/certse-ioc-converter-linux-amd64
            dist/certse-ioc-converter-linux-arm64
            dist/certse-ioc-converter-linux-arm
            README.md