on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        GOOS: ['windows', 'darwin', 'linux']
        GOARCH: ['amd64', '386', 'arm64', 'arm']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Try build for Windows, Mac and Linux
        shell: bash
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          go build -o ioconv-$OS-$ARCH
      - name: Show files and testrun linux variant
        shell: bash
        run: |
          ls -la
          ./iconv-linux-amd64